"""
IV-Switching Strategy Order Routes
====================================
REST API for per-user daily orders generated by the IV-Switching Composite Engine.

Endpoints:
  GET  /api/iv-orders/me            — Today's order for authenticated user
  GET  /api/iv-orders/me/history    — Last N days of orders
  POST /api/iv-orders/me/{id}/place — Execute order via TastyTrade
  POST /api/iv-orders/me/{id}/skip  — Mark order as skipped
  POST /api/iv-orders/admin/generate — Admin: trigger order generation manually
"""

import logging
from datetime import date, datetime, timedelta
from typing import Optional, List
from fastapi import APIRouter, HTTPException, Depends, Query
from pydantic import BaseModel

router = APIRouter()
log = logging.getLogger("IVS.OrdersAPI")


# ── Schemas ──────────────────────────────────────────────────────────────────

class OrderLeg(BaseModel):
    action:          str
    symbol:          str
    qty:             int
    instrument_type: str = "Equity Option"


class OrderResponse(BaseModel):
    id:                str
    trade_date:        str
    strategy_mode:     Optional[str] = None
    signal_type:       Optional[str] = None

    account_cash:      Optional[float] = None
    account_nlv:       Optional[float] = None
    account_bp:        Optional[float] = None
    open_zebra_count:  int = 0
    open_csp_count:    int = 0
    open_ccs_count:    int = 0
    open_sqqq_shares:  int = 0

    symbol:            Optional[str] = None
    option_type:       Optional[str] = None
    contracts:         int = 0
    capital_required:  float = 0.0
    nav_pct:           float = 0.0
    order_legs:        Optional[list] = None
    limit_price:       Optional[float] = None
    long_strike:       Optional[float] = None
    short_strike:      Optional[float] = None
    expiry_date:       Optional[str] = None

    status:            str = "PENDING"
    order_id:          Optional[str] = None
    fill_price:        Optional[float] = None
    placed_at:         Optional[str] = None
    skip_reason:       Optional[str] = None
    generation_error:  Optional[str] = None
    created_at:        Optional[str] = None


class DailyOrdersResponse(BaseModel):
    trade_date:       str
    strategy_mode:    Optional[str] = None
    account_snapshot: dict = {}
    orders:           List[OrderResponse] = []


class PlaceOrderRequest(BaseModel):
    """Body for POST /me/{id}/place"""
    refresh_token:    str   # User's TastyTrade OAuth refresh token
    account_number:   Optional[str] = None
    dry_run:          bool = False


class SkipOrderRequest(BaseModel):
    reason: Optional[str] = "User skipped"


class AdminGenerateRequest(BaseModel):
    trade_date: Optional[str] = None  # YYYY-MM-DD, default today


# ── Helper: get today's orders for a user ────────────────────────────────────

def _get_orders_for_user(user_id: str, target_date: date) -> list:
    from models.db import SessionLocal
    from models.user_daily_order import UserDailyOrder
    db = SessionLocal()
    try:
        rows = db.query(UserDailyOrder).filter(
            UserDailyOrder.user_id == user_id,
            UserDailyOrder.trade_date == target_date
        ).all()
        return [r.to_dict() for r in rows]
    finally:
        db.close()


def _dict_to_order_response(d: dict) -> OrderResponse:
    return OrderResponse(
        id=d.get('id', ''),
        trade_date=d.get('tradeDate', ''),
        strategy_mode=d.get('strategyMode'),
        signal_type=d.get('signalType'),
        account_cash=d.get('accountSnapshot', {}).get('cash'),
        account_nlv=d.get('accountSnapshot', {}).get('nlv'),
        account_bp=d.get('accountSnapshot', {}).get('buyingPower'),
        open_zebra_count=d.get('accountSnapshot', {}).get('openZebras', 0),
        open_csp_count=d.get('accountSnapshot', {}).get('openCsps', 0),
        open_ccs_count=d.get('accountSnapshot', {}).get('openCcs', 0),
        open_sqqq_shares=d.get('accountSnapshot', {}).get('openSqqqShares', 0),
        symbol=d.get('symbol'),
        option_type=d.get('optionType'),
        contracts=d.get('contracts', 0),
        capital_required=d.get('capitalRequired', 0.0),
        nav_pct=d.get('navPct', 0.0),
        order_legs=d.get('orderLegs'),
        limit_price=d.get('limitPrice'),
        long_strike=d.get('longStrike'),
        short_strike=d.get('shortStrike'),
        expiry_date=d.get('expiryDate'),
        status=d.get('status', 'PENDING'),
        order_id=d.get('orderId'),
        fill_price=d.get('fillPrice'),
        placed_at=d.get('placedAt'),
        skip_reason=d.get('skipReason'),
        generation_error=d.get('generationError'),
        created_at=d.get('createdAt'),
    )


# ── Routes ────────────────────────────────────────────────────────────────────

@router.get("/me", response_model=DailyOrdersResponse)
async def get_my_orders(
    user_id: str = Query(..., description="User ID (from JWT claims)"),
    trade_date: Optional[str] = Query(None, description="YYYY-MM-DD, default today")
):
    """
    Return today's (or specified date's) order(s) for the authenticated user.

    The `user_id` parameter should be populated server-side from the JWT token.
    In a full auth implementation, use Depends(get_current_user).
    """
    try:
        td = date.fromisoformat(trade_date) if trade_date else date.today()
        rows = _get_orders_for_user(user_id, td)

        # Build response
        mode = rows[0].get('strategyMode') if rows else None
        snapshot = rows[0].get('accountSnapshot', {}) if rows else {}
        orders = [_dict_to_order_response(r) for r in rows]

        return DailyOrdersResponse(
            trade_date=td.isoformat(),
            strategy_mode=mode,
            account_snapshot=snapshot,
            orders=orders
        )
    except Exception as e:
        log.error(f"get_my_orders error: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/me/history", response_model=List[DailyOrdersResponse])
async def get_my_order_history(
    user_id: str = Query(..., description="User ID from JWT"),
    days: int = Query(30, ge=1, le=90)
):
    """Return last N days of orders for a user, newest first."""
    try:
        from models.db import SessionLocal
        from models.user_daily_order import UserDailyOrder
        from sqlalchemy import and_

        start_date = date.today() - timedelta(days=days)
        db = SessionLocal()
        try:
            rows = db.query(UserDailyOrder).filter(
                and_(UserDailyOrder.user_id == user_id,
                     UserDailyOrder.trade_date >= start_date)
            ).order_by(UserDailyOrder.trade_date.desc()).all()

            # Group by date
            by_date: dict = {}
            for r in rows:
                td = r.trade_date.isoformat()
                if td not in by_date:
                    by_date[td] = []
                by_date[td].append(r.to_dict())

            result = []
            for td_str, day_rows in by_date.items():
                mode = day_rows[0].get('strategyMode') if day_rows else None
                snap = day_rows[0].get('accountSnapshot', {}) if day_rows else {}
                result.append(DailyOrdersResponse(
                    trade_date=td_str,
                    strategy_mode=mode,
                    account_snapshot=snap,
                    orders=[_dict_to_order_response(r) for r in day_rows]
                ))
            return result
        finally:
            db.close()
    except Exception as e:
        log.error(f"get_order_history error: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/me/{order_id}/place")
async def place_order(order_id: str, body: PlaceOrderRequest):
    """
    Execute the order via TastyTrade using the user's refresh token.

    Steps:
      1. Load order from DB
      2. Validate status == PENDING
      3. Build TastyTrade NewOrder from order_legs
      4. Place order via account.place_order()
      5. Update status=PLACED, save order_id
    """
    from models.db import SessionLocal
    from models.user_daily_order import UserDailyOrder
    from tastytrade_utils import create_user_session, get_user_account
    from tastytrade.order import (
        NewOrder, OrderLeg, OrderAction, OrderType,
        OrderTimeInForce, PriceEffect
    )
    from decimal import Decimal

    db = SessionLocal()
    try:
        order_row = db.query(UserDailyOrder).filter(
            UserDailyOrder.id == order_id
        ).first()

        if not order_row:
            raise HTTPException(status_code=404, detail="Order not found")
        if order_row.status not in ('PENDING', 'ERROR'):
            return {"status": order_row.status,
                    "message": f"Order already {order_row.status}"}
        if not order_row.order_legs:
            raise HTTPException(status_code=400, detail="Order has no legs — it is HOLD/NO_ACTION")

        # ─ Build TastyTrade session with user's token ─────────────────────────
        try:
            session = create_user_session(body.refresh_token)
            account = get_user_account(session, body.account_number)
        except Exception as e:
            raise HTTPException(status_code=401, detail=f"TastyTrade auth failed: {e}")

        # ─ Map order_legs → OrderLeg objects ─────────────────────────────────
        _action_map = {
            "BUY_TO_OPEN":   OrderAction.BUY_TO_OPEN,
            "SELL_TO_OPEN":  OrderAction.SELL_TO_OPEN,
            "BUY_TO_CLOSE":  OrderAction.BUY_TO_CLOSE,
            "SELL_TO_CLOSE": OrderAction.SELL_TO_CLOSE,
            "BUY":           OrderAction.BUY,
            "SELL":          OrderAction.SELL,
        }

        legs = []
        for leg in order_row.order_legs:
            action = _action_map.get(leg['action'])
            if not action:
                raise HTTPException(status_code=400,
                                    detail=f"Unknown leg action: {leg['action']}")
            legs.append(OrderLeg(
                instrument_type=leg.get('instrument_type', 'Equity Option'),
                symbol=leg['symbol'],
                quantity=leg['qty'],
                action=action
            ))

        # ─ Determine price effect ─────────────────────────────────────────────
        open_types = {'OPEN_CSP', 'OPEN_CCS'}
        is_credit = order_row.signal_type in open_types
        price_effect = PriceEffect.CREDIT if is_credit else PriceEffect.DEBIT

        # ─ Build and place order ──────────────────────────────────────────────
        tt_order = NewOrder(
            time_in_force=OrderTimeInForce.DAY,
            order_type=OrderType.LIMIT,
            legs=legs,
            price=Decimal(str(round(order_row.limit_price, 2))),
            price_effect=price_effect
        )

        if body.dry_run:
            response = account.place_order(session, tt_order, dry_run=True)
            return {"status": "dry_run", "order_id": None,
                    "message": "Dry run successful — order NOT placed"}

        response = account.place_order(session, tt_order, dry_run=False)
        tt_order_id = str(response.order.id) if hasattr(response, 'order') else "submitted"

        # ─ Update DB ──────────────────────────────────────────────────────────
        order_row.status   = "PLACED"
        order_row.order_id = tt_order_id
        order_row.placed_at = datetime.utcnow()
        db.commit()

        log.info(f"Placed order {tt_order_id} for row {order_id}")
        return {
            "status":    "PLACED",
            "order_id":  tt_order_id,
            "message":   "Order placed successfully",
            "signal_type": order_row.signal_type,
        }

    except HTTPException:
        raise
    except Exception as e:
        log.error(f"place_order error: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=str(e))
    finally:
        db.close()


@router.post("/me/{order_id}/skip")
async def skip_order(order_id: str, body: SkipOrderRequest):
    """Mark an order as SKIPPED (user chose not to execute)."""
    from models.db import SessionLocal
    from models.user_daily_order import UserDailyOrder

    db = SessionLocal()
    try:
        row = db.query(UserDailyOrder).filter(
            UserDailyOrder.id == order_id
        ).first()
        if not row:
            raise HTTPException(status_code=404, detail="Order not found")
        row.status = "SKIPPED"
        row.skip_reason = body.reason
        db.commit()
        return {"status": "SKIPPED", "message": "Order marked as skipped"}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
    finally:
        db.close()


@router.post("/admin/generate")
async def admin_generate_orders(body: AdminGenerateRequest):
    """
    Admin endpoint: manually trigger daily order generation.
    Useful for testing or re-running failed jobs.
    """
    import sys, os
    try:
        from datetime import date as date_type
        td = date_type.fromisoformat(body.trade_date) if body.trade_date else date_type.today()

        # Import the generator from the iv-switching-composite directory
        COMPOSITE_DIR = os.path.join(
            os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))),
            'iv-switching-composite'
        )
        sys.path.insert(0, COMPOSITE_DIR)

        from daily_order_generator import run_daily_order_generation
        result = run_daily_order_generation(td)
        return {"status": "success", "result": result}

    except Exception as e:
        log.error(f"admin_generate error: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=str(e))


# ── Internal helper (called by auto_approve.py, not via HTTP) ────────────────

def _place_iv_order_internal(order_id: str, session, account) -> dict:
    """
    Place an IV-Switching order given an already-authenticated TastyTrade
    session and account object (supplied by auto_approve.py).

    Returns a result dict with status/order_id/message.
    Raises ValueError on hard failures so caller can log and fall back.
    """
    from models.db import SessionLocal
    from models.user_daily_order import UserDailyOrder
    from tastytrade.order import (
        NewOrder, OrderLeg as TTOrderLeg, OrderAction, OrderType,
        OrderTimeInForce, PriceEffect
    )
    from decimal import Decimal

    db = SessionLocal()
    try:
        order_row = db.query(UserDailyOrder).filter(
            UserDailyOrder.id == order_id
        ).first()

        if not order_row:
            raise ValueError(f"IV-Switching order {order_id} not found in DB")
        if order_row.status not in ('PENDING', 'ERROR'):
            return {"status": order_row.status,
                    "message": f"Order already {order_row.status}",
                    "order_id": order_row.order_id}
        if not order_row.order_legs:
            return {"status": "SKIPPED",
                    "message": "HOLD/NO_ACTION — no legs to place",
                    "order_id": None}

        _action_map = {
            "BUY_TO_OPEN":   OrderAction.BUY_TO_OPEN,
            "SELL_TO_OPEN":  OrderAction.SELL_TO_OPEN,
            "BUY_TO_CLOSE":  OrderAction.BUY_TO_CLOSE,
            "SELL_TO_CLOSE": OrderAction.SELL_TO_CLOSE,
            "BUY":           OrderAction.BUY,
            "SELL":          OrderAction.SELL,
        }

        legs = []
        for leg in order_row.order_legs:
            action = _action_map.get(leg['action'])
            if not action:
                raise ValueError(f"Unknown leg action: {leg['action']}")
            legs.append(TTOrderLeg(
                instrument_type=leg.get('instrument_type', 'Equity Option'),
                symbol=leg['symbol'],
                quantity=leg['qty'],
                action=action
            ))

        is_credit = order_row.signal_type in ('OPEN_CSP', 'OPEN_CCS')
        price_effect = PriceEffect.CREDIT if is_credit else PriceEffect.DEBIT

        tt_order = NewOrder(
            time_in_force=OrderTimeInForce.DAY,
            order_type=OrderType.LIMIT,
            legs=legs,
            price=Decimal(str(round(order_row.limit_price or 0, 2))),
            price_effect=price_effect
        )

        response = account.place_order(session, tt_order, dry_run=False)
        tt_order_id = str(response.order.id) if hasattr(response, 'order') else "submitted"

        order_row.status    = "PLACED"
        order_row.order_id  = tt_order_id
        order_row.placed_at = datetime.utcnow()
        db.commit()

        log.info(f"[internal] Placed IV-Switching order {tt_order_id} for row {order_id}")
        return {
            "status":      "PLACED",
            "order_id":    tt_order_id,
            "message":     "IV-Switching order placed via auto_approve",
            "signal_type": order_row.signal_type,
        }

    finally:
        db.close()

