"""
Trade Signals Routes
====================
CRUD operations for trade signals generated by the scanner.
"""

from fastapi import APIRouter, HTTPException, Depends
from pydantic import BaseModel
from typing import List, Optional
from datetime import datetime
import uuid
import logging

router = APIRouter()
logger = logging.getLogger(__name__)

# In-memory signal storage (would be database in production)
_signals_store: List[dict] = []


class SignalCreate(BaseModel):
    """Signal creation model."""
    symbol: str
    strategy: str = "calendar_spread"
    direction: str  # bullish/bearish
    cost: float
    potential_return: float
    win_rate: float
    risk_level: str  # Low/Medium/High
    expiry: str
    details: Optional[dict] = None


class SignalResponse(BaseModel):
    """Signal response model."""
    id: str
    symbol: str
    strategy: str
    direction: str
    cost: float
    potential_return: float
    return_percent: float
    win_rate: float
    risk_level: str
    expiry: str
    status: str  # pending/approved/rejected/executed
    created_at: datetime


class SignalApproveRequest(BaseModel):
    """Signal approval request."""
    execute_immediately: bool = True


@router.get("", response_model=List[SignalResponse])
async def list_signals(
    status: Optional[str] = "pending",
    limit: int = 20
):
    """
    Get list of trade signals.
    
    Filter by status: pending, approved, rejected, executed
    """
    filtered = [s for s in _signals_store if s["status"] == status or status is None]
    return filtered[:limit]


@router.post("", response_model=SignalResponse)
async def create_signal(signal: SignalCreate):
    """
    Create a new trade signal.
    
    Called by the background scanner when it finds an opportunity.
    """
    return_percent = (signal.potential_return / signal.cost) * 100 if signal.cost > 0 else 0
    
    new_signal = {
        "id": str(uuid.uuid4()),
        "symbol": signal.symbol,
        "strategy": signal.strategy,
        "direction": signal.direction,
        "cost": signal.cost,
        "potential_return": signal.potential_return,
        "return_percent": round(return_percent, 1),
        "win_rate": signal.win_rate,
        "risk_level": signal.risk_level,
        "expiry": signal.expiry,
        "status": "pending",
        "created_at": datetime.utcnow(),
        "details": signal.details,
    }
    
    _signals_store.append(new_signal)
    logger.info(f"Created signal: {new_signal['id']} for {signal.symbol}")
    
    return SignalResponse(**new_signal)


@router.get("/{signal_id}", response_model=SignalResponse)
async def get_signal(signal_id: str):
    """Get a specific signal by ID."""
    for signal in _signals_store:
        if signal["id"] == signal_id:
            return SignalResponse(**signal)
    raise HTTPException(status_code=404, detail="Signal not found")


@router.post("/{signal_id}/approve")
async def approve_signal(signal_id: str, request: SignalApproveRequest):
    """
    Approve a signal for execution.
    
    If execute_immediately is True, the trade will be placed immediately.
    """
    for signal in _signals_store:
        if signal["id"] == signal_id:
            if signal["status"] != "pending":
                raise HTTPException(
                    status_code=400, 
                    detail=f"Signal already {signal['status']}"
                )
            
            signal["status"] = "approved"
            
            if request.execute_immediately:
                # TODO: Call trade execution service
                signal["status"] = "executed"
                logger.info(f"Executed signal: {signal_id}")
            
            return {"status": signal["status"], "message": "Signal approved"}
    
    raise HTTPException(status_code=404, detail="Signal not found")


@router.post("/{signal_id}/reject")
async def reject_signal(signal_id: str):
    """Reject a signal."""
    for signal in _signals_store:
        if signal["id"] == signal_id:
            signal["status"] = "rejected"
            return {"status": "rejected", "message": "Signal rejected"}
    
    raise HTTPException(status_code=404, detail="Signal not found")
