"""
Trade Signals Routes
====================
CRUD operations for trade signals generated by the scanner.
"""

from fastapi import APIRouter, HTTPException, Depends
from pydantic import BaseModel
from typing import List, Optional
from datetime import datetime
import uuid
import logging

router = APIRouter()
logger = logging.getLogger(__name__)

# In-memory signal storage (would be database in production)
_signals_store: List[dict] = []


class SignalCreate(BaseModel):
    """Signal creation model."""
    symbol: str
    strategy: str = "calendar_spread"
    direction: str  # bullish/bearish
    cost: float
    potential_return: float
    win_rate: float
    risk_level: str  # Low/Medium/High
    expiry: str
    details: Optional[dict] = None


class SignalResponse(BaseModel):
    """Signal response model."""
    id: str
    symbol: str
    strategy: str
    direction: str
    cost: float
    potential_return: float
    return_percent: float
    win_rate: float
    risk_level: str
    expiry: str
    status: str  # pending/approved/rejected/executed
    created_at: datetime


class SignalApproveRequest(BaseModel):
    """Signal approval request."""
    execute_immediately: bool = True


@router.get("", response_model=List[SignalResponse])
async def list_signals(
    status: Optional[str] = "pending",
    limit: int = 20
):
    """
    Get list of trade signals from PostgreSQL database.
    
    Filter by status: pending, approved, rejected, executed
    """
    try:
        from src.earnings_intelligence.database import SignalRepository
        repo = SignalRepository()
        
        # Fetch from PostgreSQL database
        db_signals = repo.get_all_signals(status=status, include_expired=False)
        
        # Convert to response format
        results = []
        for sig in db_signals[:limit]:
            signal_dict = sig.data if sig.data else {}
            signal_dict.update({
                'id': sig.id,
                'symbol': sig.symbol,
                'strategy': sig.strategy,  # CRITICAL: Include strategy from DB
                'status': sig.status,
                'created_at': sig.created_at
            })
            
            # Ensure all required fields have defaults
            if 'direction' not in signal_dict:
                signal_dict['direction'] = 'neutral'
            if 'cost' not in signal_dict:
                signal_dict['cost'] = 0.0
            if 'potential_return' not in signal_dict:
                signal_dict['potential_return'] = 0.0
            if 'return_percent' not in signal_dict:
                signal_dict['return_percent'] = 0.0
            if 'win_rate' not in signal_dict:
                signal_dict['win_rate'] = 0.0
            if 'risk_level' not in signal_dict:
                signal_dict['risk_level'] = 'Medium'
            if 'expiry' not in signal_dict:
                signal_dict['expiry'] = ''
                
            results.append(SignalResponse(**signal_dict))
        
        return results
        
    except Exception as e:
        logger.error(f"Failed to fetch signals from database: {e}")
        # Fallback to in-memory store
        filtered = [s for s in _signals_store if s["status"] == status or status is None]
        return filtered[:limit]


@router.post("", response_model=SignalResponse)
async def create_signal(signal: SignalCreate):
    """
    Create a new trade signal.
    
    Called by the background scanner when it finds an opportunity.
    """
    return_percent = (signal.potential_return / signal.cost) * 100 if signal.cost > 0 else 0
    
    new_signal = {
        "id": str(uuid.uuid4()),
        "symbol": signal.symbol,
        "strategy": signal.strategy,
        "direction": signal.direction,
        "cost": signal.cost,
        "potential_return": signal.potential_return,
        "return_percent": round(return_percent, 1),
        "win_rate": signal.win_rate,
        "risk_level": signal.risk_level,
        "expiry": signal.expiry,
        "status": "pending",
        "created_at": datetime.utcnow(),
        "details": signal.details,
    }
    
    _signals_store.append(new_signal)
    logger.info(f"Created signal: {new_signal['id']} for {signal.symbol}")
    
    return SignalResponse(**new_signal)


@router.get("/{signal_id}", response_model=SignalResponse)
async def get_signal(signal_id: str):
    """Get a specific signal by ID."""
    for signal in _signals_store:
        if signal["id"] == signal_id:
            return SignalResponse(**signal)
    raise HTTPException(status_code=404, detail="Signal not found")


@router.post("/{signal_id}/approve")
async def approve_signal(signal_id: str, request: SignalApproveRequest):
    """
    Approve a signal for execution.
    
    If execute_immediately is True, the trade will be placed immediately.
    """
    for signal in _signals_store:
        if signal["id"] == signal_id:
            if signal["status"] != "pending":
                raise HTTPException(
                    status_code=400, 
                    detail=f"Signal already {signal['status']}"
                )
            
            signal["status"] = "approved"
            
            if request.execute_immediately:
                # TODO: Call trade execution service
                signal["status"] = "executed"
                logger.info(f"Executed signal: {signal_id}")
            
            return {"status": signal["status"], "message": "Signal approved"}
    
    raise HTTPException(status_code=404, detail="Signal not found")


@router.post("/{signal_id}/reject")
async def reject_signal(signal_id: str):
    """Reject a signal."""
    for signal in _signals_store:
        if signal["id"] == signal_id:
            signal["status"] = "rejected"
            return {"status": "rejected", "message": "Signal rejected"}
    
    raise HTTPException(status_code=404, detail="Signal not found")


# =============================================================================
# THETA STRATEGY ENDPOINTS
# =============================================================================

class ThetaSignalResponse(BaseModel):
    """Theta strategy signal response."""
    id: str
    signalType: str  # ENTRY or EXIT
    symbol: str
    strike: float
    expiration: str
    entryPrice: Optional[float] = None
    exitPrice: Optional[float] = None
    contracts: int
    confidence: Optional[int] = None
    capitalRequired: Optional[float] = None
    totalPremium: Optional[float] = None
    unrealizedPnL: Optional[float] = None
    unrealizedPnLPct: Optional[float] = None
    reason: Optional[str] = None
    urgency: Optional[str] = None
    rationale: str
    status: str
    createdAt: datetime


class ThetaPositionResponse(BaseModel):
    """Theta position response."""
    position_id: str
    symbol: str
    strike: float
    expiration: str
    entry_date: str
    entry_price: float
    contracts: int
    capital_reserved: float
    premium_received: float
    current_mid: float
    unrealized_pnl: float
    unrealized_pnl_pct: float
    delta: float
    theta: float
    status: str


@router.get("/theta", response_model=List[ThetaSignalResponse])
async def list_theta_signals(
    signal_type: Optional[str] = None,
    status: Optional[str] = "pending",
    limit: int = 20
):
    """
    Get Theta strategy signals.
    
    Filter by:
    - signal_type: ENTRY or EXIT
    - status: pending, approved, executed
    """
    try:
        from signal_publisher import get_theta_signals
        signals = get_theta_signals(signal_type)
        
        if status:
            signals = [s for s in signals if s.get("status") == status]
        
        return signals[:limit]
    except Exception as e:
        logger.error(f"Error fetching theta signals: {e}")
        return []


@router.get("/theta/positions", response_model=List[ThetaPositionResponse])
async def list_theta_positions():
    """Get all open Theta strategy positions."""
    try:
        import sys, os
        sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(__file__))))
        
        from src.theta_spreads import ThetaPortfolioManager
        import config
        
        portfolio = ThetaPortfolioManager(total_capital=config.ACCOUNT_SIZE)
        positions = portfolio.get_all_positions()
        
        return [
            {
                "position_id": p.position_id,
                "symbol": p.symbol,
                "strike": p.strike,
                "expiration": p.expiration.isoformat(),
                "entry_date": p.entry_date.isoformat(),
                "entry_price": p.entry_price,
                "contracts": p.contracts,
                "capital_reserved": p.capital_reserved,
                "premium_received": p.premium_received,
                "current_mid": p.current_mid,
                "unrealized_pnl": p.unrealized_pnl,
                "unrealized_pnl_pct": p.unrealized_pnl_pct,
                "delta": p.delta,
                "theta": p.theta,
                "status": p.status
            }
            for p in positions
        ]
    except Exception as e:
        logger.error(f"Error fetching theta positions: {e}")
        return []


@router.get("/theta/portfolio")
async def get_theta_portfolio_state():
    """Get Theta portfolio summary."""
    try:
        import sys, os
        sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(__file__))))
        
        from src.theta_spreads import ThetaPortfolioManager
        import config
        
        portfolio = ThetaPortfolioManager(total_capital=config.ACCOUNT_SIZE)
        state = portfolio.get_portfolio_state()
        
        return {
            "total_capital": state.total_capital,
            "reserved_capital": state.reserved_capital,
            "available_capital": state.available_capital,
            "current_heat": state.current_heat,
            "heat_pct": state.heat_pct,
            "position_count": state.position_count,
            "open_symbols": state.open_symbols,
            "total_premium_received": state.total_premium_received,
            "total_unrealized_pnl": state.total_unrealized_pnl,
            "total_unrealized_pnl_pct": state.total_unrealized_pnl_pct
        }
    except Exception as e:
        logger.error(f"Error fetching theta portfolio: {e}")
        return {"error": str(e)}


@router.post("/theta/{signal_id}/approve")
async def approve_theta_signal(signal_id: str):
    """
    Approve a Theta signal.
    
    Marks the signal as 'approved'. The frontend will execute the actual trade
    using the user's Tastytrade credentials via the frontend API.
    """
    try:
        from signal_publisher import get_theta_signals
        
        signals = get_theta_signals()
        signal = next((s for s in signals if s.get("id") == signal_id), None)
        
        if not signal:
            raise HTTPException(status_code=404, detail="Signal not found")
        
        if signal.get("status") != "pending":
            raise HTTPException(status_code=400, detail=f"Signal already {signal.get('status')}")
        
        # Just mark as approved - frontend will execute via user credentials
        signal["status"] = "approved"
        
        logger.info(f"✅ Theta signal approved: {signal.get('symbol')} {signal.get('strike')}P")
        
        return {
            "status": "approved",
            "message": f"Theta signal {signal_id} approved. Ready for execution.",
            "signal": signal
        }
    
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error approving theta signal: {e}")
        import traceback
        logger.error(traceback.format_exc())
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/theta/run-morning-analysis")
async def run_theta_morning_analysis():
    """
    Manually trigger morning analysis.
    
    Runs: symbol selection → options analysis → entry signal generation
    """
    try:
        import sys, os
        sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(__file__))))
        
        from src.theta_spreads import ThetaScheduler
        
        scheduler = ThetaScheduler()
        scheduler.run_morning_analysis_now()
        
        return {"status": "success", "message": "Morning analysis triggered"}
    except Exception as e:
        logger.error(f"Error running morning analysis: {e}")
        return {"status": "error", "message": str(e)}


@router.post("/theta/run-position-check")
async def run_theta_position_check():
    """
    Manually trigger position monitoring.
    
    Checks all open positions for exit signals.
    """
    try:
        import sys, os
        sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(__file__))))
        
        from src.theta_spreads import ThetaScheduler
        
        scheduler = ThetaScheduler()
        scheduler.run_position_check_now()
        
        return {"status": "success", "message": "Position check triggered"}
    except Exception as e:
        logger.error(f"Error running position check: {e}")
        return {"status": "error", "message": str(e)}

