"""
UserDailyOrder Model
=====================
Stores per-user daily orders generated by the IV-Switching Composite Engine.

Each row represents a specific executable order (or HOLD/NO_ACTION) for a single
user on a single trading day, already scaled to their account NAV and reconciled
against their existing live positions.
"""

from sqlalchemy import Column, String, Boolean, DateTime, Float, Integer, Date, JSON, ForeignKey
from datetime import datetime
import uuid
from .db import Base


class UserDailyOrder(Base):
    __tablename__ = "user_daily_orders"

    id               = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    user_id          = Column(String, ForeignKey("users.id"), index=True, nullable=False)
    trade_date       = Column(Date, index=True, nullable=False)

    # ── Strategy Context ───────────────────────────────────────────────────────
    strategy_mode    = Column(String)        # A, B, C, D2, D3
    signal_type      = Column(String)        # OPEN_ZEBRA, OPEN_CSP, OPEN_CCS,
                                             # OPEN_SQQQ, CLOSE_ZEBRA, CLOSE_CSP,
                                             # HOLD, NO_ACTION

    # ── User Account Snapshot at Calculation Time ──────────────────────────────
    account_cash     = Column(Float)         # TT cash balance
    account_nlv      = Column(Float)         # TT net liquidating value (used as NAV)
    account_bp       = Column(Float)         # TT derivative buying power
    open_zebra_count = Column(Integer, default=0)
    open_csp_count   = Column(Integer, default=0)
    open_ccs_count   = Column(Integer, default=0)
    open_sqqq_shares = Column(Integer, default=0)

    # ── Order Details ──────────────────────────────────────────────────────────
    symbol           = Column(String)        # QQQM, TQQQ, QQQ, SQQQ
    option_type      = Column(String, nullable=True)  # ZEBRA, CSP, CCS, EQUITY, None
    contracts        = Column(Integer, default=0)
    capital_required = Column(Float, default=0.0)
    nav_pct          = Column(Float, default=0.0)    # capital_required / account_nlv

    # ── Exact Order Legs (TastyTrade-ready) ───────────────────────────────────
    # Example ZEBRA:
    # [
    #   {"action": "BUY_TO_OPEN",  "symbol": "QQQM  260606C00480000", "qty": 2},
    #   {"action": "SELL_TO_OPEN", "symbol": "QQQM  260606C00490000", "qty": 1}
    # ]
    order_legs       = Column(JSON, nullable=True)

    # ── Pricing ────────────────────────────────────────────────────────────────
    limit_price      = Column(Float, nullable=True)   # Net debit/credit per unit
    long_strike      = Column(Float, nullable=True)
    short_strike     = Column(Float, nullable=True)
    expiry_date      = Column(Date, nullable=True)

    # ── Status Tracking ────────────────────────────────────────────────────────
    # State machine: PENDING → CONFIRMED → PLACED → FILLED
    #                PENDING → SKIPPED
    status           = Column(String, default="PENDING")
    order_id         = Column(String, nullable=True)   # TastyTrade order ID once placed
    fill_price       = Column(Float, nullable=True)    # Actual fill price
    placed_at        = Column(DateTime, nullable=True)
    filled_at        = Column(DateTime, nullable=True)
    skip_reason      = Column(String, nullable=True)

    # ── Metadata ───────────────────────────────────────────────────────────────
    created_at       = Column(DateTime, default=datetime.utcnow)
    updated_at       = Column(DateTime, onupdate=datetime.utcnow)
    generation_error = Column(String, nullable=True)   # Error msg if generation failed

    def to_dict(self) -> dict:
        return {
            "id":               self.id,
            "userId":           self.user_id,
            "tradeDate":        self.trade_date.isoformat() if self.trade_date else None,
            "strategyMode":     self.strategy_mode,
            "signalType":       self.signal_type,
            "accountSnapshot": {
                "cash":           self.account_cash,
                "nlv":            self.account_nlv,
                "buyingPower":    self.account_bp,
                "openZebras":     self.open_zebra_count,
                "openCsps":       self.open_csp_count,
                "openCcs":        self.open_ccs_count,
                "openSqqqShares": self.open_sqqq_shares,
            },
            "symbol":           self.symbol,
            "optionType":       self.option_type,
            "contracts":        self.contracts,
            "capitalRequired":  self.capital_required,
            "navPct":           round(self.nav_pct * 100, 2) if self.nav_pct else 0,
            "orderLegs":        self.order_legs,
            "limitPrice":       self.limit_price,
            "longStrike":       self.long_strike,
            "shortStrike":      self.short_strike,
            "expiryDate":       self.expiry_date.isoformat() if self.expiry_date else None,
            "status":           self.status,
            "orderId":          self.order_id,
            "fillPrice":        self.fill_price,
            "placedAt":         self.placed_at.isoformat() if self.placed_at else None,
            "filledAt":         self.filled_at.isoformat() if self.filled_at else None,
            "skipReason":       self.skip_reason,
            "createdAt":        self.created_at.isoformat() if self.created_at else None,
        }
